<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyVersion>1.1.1</AssemblyVersion>
        <FileVersion>1.1.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="CommunityToolkit.Mvvm">
            <HintPath>..\..\..\.nuget\packages\communitytoolkit.mvvm\8.2.1\lib\net6.0\CommunityToolkit.Mvvm.dll</HintPath>
        </Reference>
        <Reference Include="SukiUI">
            <HintPath>..\..\..\.nuget\packages\sukiui\6.0.2\lib\netstandard2.0\SukiUI.dll</HintPath>
        </Reference>
        <Reference Include="TickerQ.EntityFrameworkCore">
          <HintPath>..\..\..\.nuget\packages\tickerq.entityframeworkcore\2.5.3\lib\netstandard2.1\TickerQ.EntityFrameworkCore.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.5" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0"/>
        <PackageReference Include="SukiUI" Version="6.0.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\YASAM.Services.Client\YASAM.Services.Client.csproj"/>
        <ProjectReference Include="..\YASAM.SteamInterface\YASAM.SteamInterface.csproj"/>
    </ItemGroup>

</Project>
