<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyVersion>1.1.1</AssemblyVersion>
        <FileVersion>1.1.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\YASAM.SteamInterface.Executor\YASAM.SteamInterface.Executor.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="HtmlAgilityPack" Version="1.12.2" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8" />
    </ItemGroup>

</Project>
