<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyVersion>1.1.1</AssemblyVersion>
        <FileVersion>1.1.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\YASAM.Data\YASAM.Data.csproj"/>
    </ItemGroup>

</Project>
