using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;


namespace YASAM.SourceGenerators;

[Generator]
public class SourceGeneratorAddYasamWindows : IIncrementalGenerator
{
    private const string ClassName = "GenericHostAvaloniaApplication";
    private const string Namespace = "YASAM";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax,
                (ctx, _) => FindWindowClassDeclarations(ctx))
            .Where(x => x is not null);
        
        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()),
            ((ctx, t) => Generate(ctx, t.Left, t.Right!)));
    }
    
    private static ClassDeclarationSyntax? FindWindowClassDeclarations(
        GeneratorSyntaxContext context)
    {
        var classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;

        if (classDeclarationSyntax.Identifier.ToString().EndsWith("Window"))
            return classDeclarationSyntax;
        
        return null;
    }
    
    private void Generate(SourceProductionContext context, Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classDeclarations)
    {
        var windowsToRegister = new List<string>();
        foreach (var classDeclarationSyntax in classDeclarations)
        {
            var semanticModel = compilation.GetSemanticModel(classDeclarationSyntax.SyntaxTree);

            if (semanticModel.GetDeclaredSymbol(classDeclarationSyntax) is not INamedTypeSymbol classSymbol)
                continue;
            
            var className = classDeclarationSyntax.Identifier.Text;
            windowsToRegister.Add(className);
        }
        
        
        var stringBuilder = new StringBuilder();
        
        stringBuilder.AppendLine("// <auto-generated/>");
        stringBuilder.AppendLine("using System;");
        stringBuilder.AppendLine("using Microsoft.Extensions.Configuration;");
        stringBuilder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        stringBuilder.AppendLine("using YASAM.Views;");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"namespace {Namespace};");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"public abstract partial class {ClassName}<TAvaloniaApplication>");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("      private static void AddWindows(IServiceCollection services)");
        stringBuilder.AppendLine("      {");
        foreach (var window in windowsToRegister)
        {
            stringBuilder.AppendLine($"             services.AddSingleton<{window}>();");
        }
        stringBuilder.AppendLine("      }");
        stringBuilder.AppendLine("}");
        
        context.AddSource($"{ClassName}.Windows.g.cs", SourceText.From(stringBuilder.ToString(), Encoding.UTF8));
        
        
    }
}