using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Runtime;
using System.Text;
using System.Xml.Schema;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace YASAM.SourceGenerators;

[Generator]
public class SourceGeneratorAddYasamViewModels : IIncrementalGenerator
{
    private const string ClassName = "GenericHostAvaloniaApplication";
    private const string Namespace = "YASAM";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        Debugger.Launch();
        
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax,
                (ctx, _) => FindViewClassDeclarations(ctx))
            .Where(x => x is not null);
        
        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()),
            ((ctx, t) => Generate(ctx, t.Left, t.Right.SelectMany(x => x).Distinct())));
    }
    
    private static List<ITypeSymbol>? FindViewClassDeclarations(
        GeneratorSyntaxContext context)
    {
        var assemblies = context.SemanticModel.Compilation.SourceModule.ReferencedAssemblySymbols
            .Where(x => x.Name.Contains("YASAM"));

        var discoveredTypes = new List<ITypeSymbol>();
        foreach (var assembly in assemblies)
        {
            var main = assembly.Identity.Name.Split('.').Aggregate(assembly.GlobalNamespace, (s, c) => s.GetNamespaceMembers().Single(m => m.Name.Equals(c)));
            var types = GetAllTypes(main).ToList();

            if (types.Any())
            {
                discoveredTypes.AddRange(types);
            }
        }
        return discoveredTypes;
    }
    
    private static IEnumerable<ITypeSymbol> GetAllTypes(INamespaceSymbol root)
    {

            foreach (var namespaceOrTypeSymbol in root.GetMembers().Where(x => x.Name.EndsWith("ViewModel")))
            {
                if (namespaceOrTypeSymbol is INamespaceSymbol @namespace) foreach (var nested in GetAllTypes(@namespace)) yield return nested;

                else if (namespaceOrTypeSymbol is INamedTypeSymbol type
                         && (type.Constructors.IsEmpty 
                             ||   type.Constructors.SelectMany(x => x.Parameters).All(c => (c.Type.TypeKind == TypeKind.Interface || c.Type.Name.EndsWith("ViewModel"))))
                         )
                    yield return type;
            }
    }
    
    private void Generate(SourceProductionContext context, Compilation compilation,
        IEnumerable<ITypeSymbol> types)
    {
        var namespacesToAdd = types.Select(x => x.ContainingNamespace.ToString()).Distinct();
        

        
            // Itterate the types here, match class -> interface and construct the code as needed
            
            var stringBuilder = new StringBuilder();
        
            stringBuilder.AppendLine("// <auto-generated/>");
            stringBuilder.AppendLine("using System;");
            stringBuilder.AppendLine("using Microsoft.Extensions.Configuration;");
            stringBuilder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            
            foreach (var discoveredNamespace in namespacesToAdd.Distinct())
            {
                stringBuilder.AppendLine($"using {discoveredNamespace};");
            }
            
            stringBuilder.AppendLine();
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"namespace {Namespace};");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"public abstract partial class {ClassName}<TAvaloniaApplication>");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("      public static void AddViewModels(IServiceCollection services)");
            stringBuilder.AppendLine("      {");
            foreach (var type in types)
            {
                stringBuilder.AppendLine($"             services.AddSingleton<{type.Name}>();");
            }
            stringBuilder.AppendLine("      }");
            stringBuilder.AppendLine("}");
        
            context.AddSource($"{ClassName}.ViewModels.g.cs", SourceText.From(stringBuilder.ToString(), Encoding.UTF8));
    }
}